# Generated by Django 4.2.15 on 2024-09-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idevento', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('idevento_calendar', models.CharField(max_length=26)),
            ],
            options={
                'db_table': 'evento',
            },
        ),
    ]
